crm/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    
    path('',views.homepage,name=''),
    path('about_us',views.about_us,name='about_us'),
    path('aboutloggedin', views.aboutloggedin, name='aboutloggedin'),
    path('contact_us',views.contact_us,name='contact_us'),
    path('contactloggedin',views.contactloggedin,name='contactloggedin'),
    
    path('registration',views.registration,name='registration'),
    path('verify',views.verify,name='verify'),    
    path('my_login',views.my_login,name='my_login'),
    path('user_logout',views.user_logout, name='user_logout'),

    path('dashboard',views.dashboard,name='dashboard'),
    path('profile',views.profile,name='profile'),
    path('terms', views.terms, name='terms'),
    path('privpolicy', views.privpolicy, name='privpolicy'),
    path('add_product',views.add_product,name='add_product'),
    path('my_products',views.my_products,name='my_products'),
    path('my_bids',views.my_bids,name='my_bids'),
    # path('coming_soon_product_detail/<pid>/',views.coming_soon_product_detail,name='coming_soon_product_detail'),
    # path('closed_product_detail/<pid>/',views.closed_product_detail,name='closed_product_detail'),
    
    path('auction',views.auction,name='auction'),
    path('category_view/<cid>/',views.category_view,name='category_view'),
    path('product_detail/<pid>/',views.product_detail,name='product_detail'),  
    path('place_bid/<pid>/', views.place_bid, name='place_bid'),
    path('shipping_details/<pid>/', views.shipping_details, name='shipping_details'),
    path('payment/<pid>/', views.payment, name='payment'),
    path('success/', views.success, name='success'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elevate/urls.py
from django.contrib import admin
from django.urls import path , include


# admin.site.site_header = "Auction House Admin"

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('crm.urls'))
]

crm/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,User
from django.contrib.auth.models import Group, Permission

from django.contrib.auth.models import User
from PIL import Image
from datetime import datetime, timedelta
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe
from django.utils import timezone


# Create your models here.



class CustomUser(AbstractUser):
# ignore this model just a sample for testing
# try this for upcoming projects
    birthday = models.DateField(null=True, blank=True)
    address = models.TextField(blank=True, null=True)  # Add the 'address' field
    groups = models.ManyToManyField(Group, verbose_name='groups', blank=True, related_name='customuser_groups')
    user_permissions = models.ManyToManyField(Permission, verbose_name='user permissions', blank=True, related_name='customuser_permissions')

class Contact(models.Model):
    sno = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=13)
    message = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True, blank=True)
    
    def __str__(self) :
        return 'Message from ' + self.first_name + ' - ' + self.email
    

class Profile(models.Model):

    user=models.OneToOneField(User,on_delete=models.CASCADE)

    image=models.ImageField(default='default.jpg',upload_to='profile_pics')

    birthday = models.DateField(null=True, blank=True)
    address = models.TextField(blank=True, null=True)
    phone = models.CharField(max_length=13,blank=True, null=True)

    DisplayFields = ['id','user','address','phone','profile_image','birthday']
    SearchableFields = ['user__username','user__first_name','user__last_name']
    FilterFields=['address']

    def __str__(self) :
        return f'{self.user.username} Profile'
    
    def profile_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url)) 

    def save(self,*args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if  img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

class Category(models.Model):

    cid = ShortUUIDField(unique=True,length=10,max_length=20,prefix='cat',alphabet='abcdefgh12345')
    title=models.CharField(max_length=100, default="Items")
    image=models.ImageField(default='default.jpg',upload_to='category_pics')

    class Meta:
        verbose_name_plural = "Categories"

    def category_image(self):
        return mark_safe('<img src= "%s" width="50" height="50"/>' % (self.image.url))
    
    def __str__(self) :
        return self.title

    def save(self,*args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if  img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)
    
class Seller(models.Model):

    sid = ShortUUIDField(unique=True,length=10,max_length=20,prefix='sel',alphabet='abcdefgh12345')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    title=models.CharField(max_length=100, default="")
    # image=models.ImageField(default='default.jpg',upload_to='product_pics')
    description = models.TextField(null=True,blank=True, default="I am an Ama=azing Seller")

    address=models.CharField(max_length=100, default="123 Main Street London")
    contact=models.CharField(max_length=100, default="+91 (1234) 567890")


    class Meta:
        verbose_name_plural = "Sellers"

    def __str__(self) :
        return self.title  
    

class Product(models.Model):
    pid = ShortUUIDField(unique=True, length=10, max_length=20, alphabet='abcdefgh12345')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name="category")
    total_bids = models.IntegerField(default=0)
    highest_bid = models.IntegerField(default=0)  # New field for highest bid
    winner_details = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='won_products')
    shipping_details_submitted = models.BooleanField(default=False)

    product_name = models.CharField(max_length=100, default="Items")
    image = models.ImageField(default='default.jpg', upload_to='product_pics')
    description = models.TextField(null=True, blank=True, default="This is the product")

    min_price = models.DecimalField(max_digits=10, decimal_places=2, default=2000)    
    price_interval = models.DecimalField(max_digits=10, decimal_places=2, default=100)

    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()

    class Meta:
        verbose_name_plural = "Products"

    def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50"/>' % self.image.url)

    def __str__(self):
        return self.product_name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def status(self):
        current_time = datetime.now().time()
        if self.start_time <= current_time < self.end_time:
            return "Live"
        elif current_time < self.start_time:
            return "Upcoming"
        elif current_time > self.end_time:
            return "Closed"
        else:
            return "Unknown"

    @classmethod
    def place_bid(cls, user, product, amount):
        product.total_bids += 1

        # Check if the bid amount is higher than the current highest bid
        if amount > product.highest_bid:
            product.highest_bid = amount
            product.winner_details = user  # Set the winner_details field to the user who placed the bid
            product.save()

        bid = Bid.objects.create(user=user, product=product, amount=amount)

        # Create bid history
        BidHistory.objects.create(product=product, user=user, amount=amount, timestamp=timezone.now())

        return bid

    def is_live_for_bidding(self):
        current_datetime = datetime.now()
        return self.date == current_datetime.date() and self.start_time <= current_datetime.time() < self.end_time

    def is_valid_bid(self, amount):
        """
        Check if the bid amount is valid (higher than the current highest bid and follows the price interval).
        """
        current_highest_bid = self.highest_bid
        price_interval = self.price_interval
        
        # Calculate the minimum valid bid amount based on the current highest bid and price interval
        minimum_bid_amount = current_highest_bid + price_interval
        
        return amount >= minimum_bid_amount
    
    def total_bids_count(self):
    
        return self.bid_history.count()

    def get_winner(self):
        if self.bid_history.exists():
            highest_bid = self.bid_history.order_by('-amount').first()
            return highest_bid.user.username
        else:
            return "No winner yet"

    @property
    def winner(self):
        return self.get_winner()


class Bid(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='bids')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Bid by {self.user.username} on {self.product.product_name}"

class BidHistory(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='bid_history')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Bid history for {self.product.product_name} by {self.user.username}"



class ShippingDetails(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='shipping_details')
    address = models.TextField(blank=False, null=False)
    city = models.CharField(max_length=100,blank=False, null=False)
    state = models.CharField(max_length=100,blank=False, null=False)
    country = models.CharField(max_length=100,blank=False, null=False)
    pincode = models.CharField(max_length=6,blank=False, null=False)

    def __str__(self):
        return f"Shipping details of {self.product.product_name} for {self.user.first_name} {self.user.last_name} "


class Payment(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='payment')

    razor_pay_order_id = models.CharField(max_length=100,blank=True, null=True)
    razor_pay_payment_id = models.CharField(max_length=100,blank=True, null=True)
    razor_pay_payment_signature = models.CharField(max_length=100,blank=True, null=True)
    
    paid = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username} - {self.product.product_name}"

crm/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from django import forms
from .models import Category, CustomUser,Profile,Product,ShippingDetails
from django.forms.widgets import PasswordInput,TextInput
from datetime import datetime, timedelta
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import Bid


# Validate that the given date is in the future (starting from tomorrow).
    
# def validate_future_date(value):
    
#     if value <= datetime.now().date() + timedelta(days=1):
#         raise ValidationError(
#             _('Date must start from tomorrow.'),
#             params={'value': value},
#         )



# Create a user/register

class CreateUserForm(UserCreationForm):

    birthday = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}), required=False, help_text='Format: YYYY-MM-DD')
    address = forms.CharField(widget=forms.Textarea(attrs={'rows': 3}), required=False, help_text='Enter your address here.')

    class Meta:

        model = CustomUser
        fields = ['first_name','last_name','username', 'email','password1','password2','birthday','address']
    
    # def __init__(self, *args, **kwargs):
    #     super(CreateUserForm, self).__init__(*args, **kwargs)
    #     self.fields['birthday'].widget.attrs['type'] = 'date'
    #     self.fields['address'].widget.attrs['rows'] = 3
    #     self.fields['address'].widget.attrs['placeholder'] = 'Enter your address here.'
    #     self.fields['birthday'].help_text = 'Format: YYYY-MM-DD'
# Authenticate the user
        
class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())
    

class UserUpdateForm(forms.ModelForm):
    email= forms.EmailField()

    class Meta:

        model = User
        fields = ['first_name','last_name','username', 'email']

class ProfileUpdateForm(forms.ModelForm):

    birthday = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}), required=False, help_text='Format: DD-MM-YYYY')
    address = forms.CharField(widget=forms.Textarea(attrs={'rows': 1}), required=False, help_text='Enter your address here.')
    phone = forms.CharField(widget=forms.TextInput(attrs={'type': 'number'}), min_length=10)
    
    

    class Meta:
        model=Profile
        fields = ['image','phone','birthday','address']


class ProductForm(forms.ModelForm):

    # date = forms.DateField(validators=[validate_future_date])
    
    class Meta:
        model = Product
        fields = ['user', 'Category', 'product_name', 'image', 'min_price', 'price_interval', 'date', 'start_time', 'end_time', 'description']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3}),
            'date': forms.DateInput(attrs={'type': 'date'}),
            'start_time': forms.TimeInput(attrs={'type': 'time'}),
            'end_time': forms.TimeInput(attrs={'type': 'time'}),
        }

    def __init__(self, user, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['Category'].queryset = Category.objects.all()  # Update queryset for category field
        self.fields['user'].widget = forms.HiddenInput()
        self.fields['user'].required = False  # Make user field not required

    # def clean(self):
    #     cleaned_data = super().clean()
    #     start_time = cleaned_data.get("start_time")
    #     end_time = cleaned_data.get("end_time")

    #     # Validate start time and end time
    #     if start_time and end_time:
    #         start_datetime = datetime.combine(datetime.now().date(), start_time)
    #         end_datetime = datetime.combine(datetime.now().date(), end_time)

    #         if start_datetime >= end_datetime:
    #             raise ValidationError(_("End time must be greater than start time."))

    #         # Validate the time difference between start time and end time
    #         time_diff = end_datetime - start_datetime
    #         if time_diff.seconds not in (3600, 7200):  # Check if the difference is not exactly 1 or 2 hours
    #             raise ValidationError(_("The difference between start time and end time must be either 1 or 2 hours."))

    #     return cleaned_data

   
    def clean(self):
        cleaned_data = super().clean()
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")

        # Validate start time and end time
        if start_time and end_time:
            start_datetime = datetime.combine(datetime.now().date(), start_time)
            end_datetime = datetime.combine(datetime.now().date(), end_time)

            if start_datetime >= end_datetime:
                raise ValidationError(_("End time must be greater than start time."))

            # Validate the time difference between start time and end time
            time_diff = end_datetime - start_datetime
            if not (timedelta(hours=1) <= time_diff <= timedelta(hours=2)):  # Check if the difference is not between 1 and 2 hours
                raise ValidationError(_("The difference between start time and end time must be between 1 and 2 hours."))

        return cleaned_data

class BidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ['amount']


class ShippingDetailsForm(forms.ModelForm):

    address = forms.CharField(widget=forms.TextInput(attrs={'rows': 1}), required=True, help_text='Enter your address here.')
    city = forms.CharField(widget=forms.TextInput(attrs={'rows': 1}), required=True, help_text='Enter your city here.')
    state = forms.CharField(widget=forms.TextInput(attrs={'rows': 1}), required=True, help_text='Enter your state here.')
    country = forms.CharField(widget=forms.TextInput(attrs={'rows': 1}), required=True, help_text='Enter your country here.')
    pincode = forms.CharField(widget=forms.NumberInput(attrs={'min': 100000}), required=True, help_text='Enter your pincode here.')

    class Meta:
        model = ShippingDetails
        fields = ['address', 'city', 'state', 'country', 'pincode']

crm/templates/crm/contact_us.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'crm/images/favicon.ico' %}"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <title>Contact Us</title>
    <link rel="stylesheet" href="{% static 'crm/style.css'%}" />
  </head>

  <body>
    <nav>
      <a href="#"><img src="{% static 'crm/images/logo.png' %}" alt="" /></a>
      <div id="navbar">
        <button class="btn"><a href="{% url 'registration' %}">Signup</a></button>
        <button class="btn"><a href="{% url 'my_login' %}">Login</a></button>
      </div>
    </nav>

    <div id="box">
      <ul id="containar">
        <li><a href="{% url '' %}">Home</a></li>
        <li><a href="{% url '' %}">Auction</a></li>
        <li><a href="{% url '' %}">How It works</a></li>
        <li><a href="{% url '' %}">Auctioneers</a></li>
        <li><a href="{% url 'about_us' %}">About Us</a></li>
        <li><a class="active" href="#">Contact Us</a></li>
      </ul>
    </div>

    <section id="contact" class="section-p1">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>Message : </strong> {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
          <h2>Contact Us</h2>
      <p>Any question or remarks? Just write us a message!</p>
      <div class="contact-box">
        <div  class="contact-box-left">
          <h3>Contact Information</h3>
          <p>Say something to start !</p>
          <div class="details">
            <li>
              <i class="fa fa-phone"></i>
              <span>+91 7600096432</span>
            </li>
            <li>
              <i class="fa fa-envelope"></i>
              <span>jvpatel2003@gmail.com</span>
            </li>
            <li>
              <i class="fa fa-map-marker"></i>
              <span
                >B-604/605, Ganesh Glory 11 Jagatpur Rd, SG Highway,Ahmedabad,Gujarat</span
              >
            </li>
          </div>
        </div>
        <div class="contact-box-right">
          <form method="POST" action="/contact_us">
            {% csrf_token %}
            <input type="text" name="first_name" placeholder="First Name" />
            <input type="text" name="last_name" placeholder="Last Name" /><br />
            <input type="email" name="email" placeholder="Email" />
            <input type="phone" name="phone" placeholder="Phone Number" />
            <h5>Select Subject?</h5>
            <input type="checkbox" />
            <label>General Inquiry</label>
            <input type="checkbox" />
            <label>Suggestion</label>
            <input type="checkbox" />
            <label>Complain</label><br />
            <h6>Message</h6>
            <input type="text1" name="message" placeholder="Write your message.." />
            <button class="contact-btn" type="submit" value="submit">Send Message</button>
            
          </form>
        </div>
      </div>
    </section>

    <footer class="section-p1">
       <div class="col">
        <img class="logo" src="{% static 'crm/images/logo2.png'%}" alt="">
        <h4>Connect</h4>
        <p>
          <strong>Address : </strong>B-604/605, Ganesh Glory 11 Jagatpur Rd, SG Highway,Ahmedabad,Gujarat 382470
        </p>
        <p><strong>Phone : </strong>07600096432</p>
        <p><strong>Hours : </strong>10:00 AM - 7:00 PM, Mon - Sat</p>
      </div>
        <div class="col">
        <h4>About</h4>
        <a href="/about_us">About Us</a>
        <a href="/privpolicy">Privacy Policy</a>
        <a href="/terms">Terms & Conditions</a>

      </div>
      <div class="col">
        <h4>My Account</h4>
        <a href="/my_login">Sign In</a>
        <a href="/my_login">View My Bids</a>
<!--        <a href="#">My Wishlist</a>-->
<!--        <a href="#">Track My Order</a>-->
        <a href="/contact_us">Help</a>
      </div>
        <div class="col">
            <h4>Follow Us</h4>
            <div class="icon">
                <a href="#" class="fa fa-facebook"></a>
                <a href="#" class="fa fa-twitter"></a>
                <a href="#" class="fa fa-instagram"></a>
                <a href="#" class="fa fa-pinterest"></a>
            </div>
        </div>
    </footer>

    <section id="end" class="section-p1">
      <h4>@ 2023 Copyright, All Rights Reserved</h4>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script> 
  </body>
</html>

crm/templates/crm/navbar.html
{%load static %}
<link rel="stylesheet" href="{% static 'crm/style.css'%}" />

<section id="box">
  <ul id="containar">
    <li><a class="active" href="index.html">Home</a></li>
    <li><a href="#live-auction">Auction</a></li>
    <li><a href="#auct">Auctioneers</a></li>
    <li><a href="#works">How It works</a></li>
    <li><a href="about_us.html">About Us</a></li>
    <li><a href="contact_us.html">Contact Us</a></li>
  </ul>
</section>

crm/templates/crm/shipping_details.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'crm/images/favicon.ico' %}"
    />
    <title>Shipping Detail</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link rel="stylesheet" href="{% static 'crm/style.css'%}" />
  </head>
  <body>
    <nav>
      <a href=""><img src="{% static 'crm/images/logo.png' %}" alt=""></a>
      <div id="navbar">
        <p style="color: white; font-size: 24px">Hello, {{user.username}}</p>

        <a class="profile-pic" href="{% url  'profile' %}"
          ><img
            class="rounded-circle shadow-4"
            style="
              width: 80px;
              vertical-align: middle;
              width: 50px;
              height: 50px;
              border-radius: 50%;
              margin-left: 10px;
            "
            alt="Avatar"
            src="{{ user.profile.image.url }}"
        /></a>
      </div>
    </nav>

    <section id="box">
      <ul id="containar">
        <li><a href="{% url 'dashboard' %}">Home</a></li>
        <li><a href="{% url 'my_products' %}">My Products</a></li>
        <li>
          <a href="{% url 'add_product' %}">Add Products</a>
        </li>
        <li><a class="active" href="{% url 'auction' %}">Auction</a></li>
        <li><a href="{% url 'my_bids' %}">My Bids</a></li>
        <li><a href="{% url 'user_logout' %}">Logout</a></li>
      </ul>
    </section>
    <div class="section-p1">
      <img class="center" src="{% static 'crm/images/payment-1.png' %}" alt="">
    </div>
    {% comment %}
    <form method="POST">
      {% csrf_token %} {{ form.as_p }}

      <button type="submit">Submit</button>
    </form>
    {% endcomment %}

    <section id="profile_product_name" class="section-p1">
      <div class="tabContainer">
        <div class="buttonContainer">
          <button style="color: white; background-color: #1f1c14">
            Shipping Details
          </button>
        </div>

        <div class="tabPanel section-p1">
          <div class="add_form">
            <form method="POST">
              {% csrf_token %}
              <div class="input_row">
                <div class="input_group">
                  <label for="">First Name</label><br />
                  <p>{{ winner.first_name }}</p><hr>
                </div>
                <div class="input_group">
                  <label for="">Last Name</label><br />
                  <p>{{ winner.last_name }}</p><hr>
                </div>
              </div>
              <div class="input_row">
                <div class="input_group">
                  <label for="">Phone No.</label><br />
                  <p>Phone: {{ winner.profile.phone }}</p><hr>
                </div>
                <div class="input_group">
                  <label for="">Email Id.</label><br />
                  <p>Email: {{ winner.email }}</p><hr>
                </div>
              </div>

              <label for="id_address">Address:</label>
              <input
              type="text"
                name="address"
                cols="1"
                rows="1"
                required
                aria-describedby="id_address_helptext"
                id="id_address"
              ></input>
              <div class="input_row">
                <div class="input_group">
                  <label for="id_state">State:</label>
                  <input
                    type="text"
                    name="state"
                    rows="1"
                    required
                    aria-describedby="id_state_helptext"
                    id="id_state"
                  />
                </div>
                <div class="input_group">
                  <label for="id_city">City:</label>
                  <input
                    type="text"
                    name="city"
                    rows="1"
                    required
                    aria-describedby="id_city_helptext"
                    id="id_city"
                  />
                </div>
              </div>

              <div class="input_row">
                <div class="input_group">
                  <label for="id_pincode">Pincode:</label>
                  <input
                    type="number"
                    name="pincode"
                    min="100000"
                    required
                    aria-describedby="id_pincode_helptext"
                    id="id_pincode"
                  />
                </div>
                <div class="input_group">
                  <label for="id_country">Country:</label>
                  <input
                    type="text"
                    name="country"
                    rows="1"
                    required
                    aria-describedby="id_country_helptext"
                    id="id_country"
                  />

                </div>
              </div>
              <div class="pay_nots">
                <span>Consent : I consent and verify that the data provided by me is valid, in any case of
                    misleading or inappropriate action by me, i will be heal responsiable and legal action can be
                    taken.</span>
                <br><br>
                <li>Note : External service charges may be applied for your order other than your bid.
                </li>
                <br>
            </div>
              <button class="payment_btn" type="submit">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </section>
    <script src="script.js"></script>
    {% comment %}
    <button type="submit" id="rzp-button1">Pay with Razorpay</button> {%
    endcomment %} {% comment %}
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>
      var options = {
        key: "rzp_test_HLUDc0d2oVKUYA", // Enter the Key ID generated from the Dashboard
        amount: "{{payment.amount}}", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
        currency: "INR",
        name: "Auction House",
        description: "Explore Bid Sell",
        image: "https://example.com/your_logo",
        order_id: "{{payment.id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
        handler: function (response) {
          window.location.href =
            "http://127.0.0.1:8000/success/?razorpay_payment_id=" +
            response.razorpay_payment_id +
            "&razorpay_order_id=" +
            response.razorpay_order_id +
            "&razorpay_signature=" +
            response.razorpay_signature;

          //alert(response.razorpay_payment_id);
          //alert(response.razorpay_order_id);
          //alert(response.razorpay_signature);
        },
        theme: {
          color: "#3399cc",
        },
      };
      var rzp1 = new Razorpay(options);
      rzp1.on("payment.failed", function (response) {
        alert(response.error.code);
        alert(response.error.description);
        alert(response.error.source);
        alert(response.error.step);
        alert(response.error.reason);
        alert(response.error.metadata.order_id);
        alert(response.error.metadata.payment_id);
      });
      document.getElementById("rzp-button1").onclick = function (e) {
        rzp1.open();
        e.preventDefault();
      };
    </script>
    {% endcomment %}
  </body>
</html>